In [5]:
import numpy as np

# define binary operations

def binary_addition(a, b):
    return a ^ b

def binary_multiplication(a, b):
    return a & b

#compute row echelon form

def encoding(matrix):
    rows, cols = matrix.shape
    lead = 0

    for r in range(rows):
        if lead >= cols:
            break

        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if cols == lead:
                    break

        matrix[[i, r]] = matrix[[r, i]]

        if matrix[r, lead] != 0:
            matrix[r] = binary_multiplication(matrix[r], matrix[r, lead])

        for j in range(rows):  # Loop again
            if j != r:
                factor = matrix[j, lead]
                matrix[j] = binary_addition(matrix[j], binary_multiplication(matrix[r], factor))

        lead += 1
    
    H_hat = matrix

# Extract matrix 'P'
    P = matrix[:, cols//2:]

# Create matrix G from H_hat, set data type for no floating points
    G = np.vstack((P, np.eye(rows))).astype(np.uint8)
    
    print("H_hat =")
    print(H_hat)
    print("G =")
    print(G)

encoding(np.array([[1, 1, 1, 1, 0, 0],
                    [0, 0, 1, 1, 0, 1],
                    [1, 0, 0, 1, 1, 0]]))


H_hat =
[[1 0 0 1 1 0]
 [0 1 0 1 1 1]
 [0 0 1 1 0 1]]
G =
[[1 1 0]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
